name: jalinanweb
services:
  - name: web
    git:
      branch: main
      repo_clone_url: https://github.com/jalinanorg/jalinanweb.git
    build_command: npm install && npm run build
    run_command: npm start
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
    http_port: 4173
